name: EgressPoint
favicon: null
layout_spectrum: 0.89388
typography_spectrum: 0.84184
title: EgressPoint
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b2acb0'
    - '#302f2d'
    - '#ffffff'
    - '#5f666e'
    - '#ffb2ae'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
