name: EgressPoint
favicon: null
typography_spectrum: 0.32857
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b2acb0'
    - '#302f2d'
    - '#ffffff'
    - '#5f666e'
    - '#ffb2ae'
  brandStrength: 0.1875
  lightness: 0.3125
  saturation: 0.75
  rhythmicContrast: 0.75
purpose:
  - name: awareness
    item: b5448d40-ca2d-483b-a861-d73ec7b4aeae
    url: null
